# Generated by Django 5.1 on 2026-01-31 20:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0003_alter_asignatura_options_alter_calificacion_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaCalificaciones',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(choices=[('CREAR', 'Crear'), ('ACTUALIZAR', 'Actualizar'), ('ELIMINAR', 'Eliminar')], max_length=20)),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('fecha_accion', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': 'Auditorías',
                'ordering': ['-fecha_accion'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id_configuracion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_institucion', models.CharField(default='Institución Educativa', max_length=200)),
                ('director', models.CharField(blank=True, max_length=200, null=True)),
                ('anio_lectivo_actual', models.CharField(default='2024-2025', max_length=20)),
                ('trimestre_actual', models.IntegerField(choices=[(1, 'Primer Trimestre'), (2, 'Segundo Trimestre'), (3, 'Tercer Trimestre')], default=1)),
                ('porcentaje_formativo', models.IntegerField(default=70, verbose_name='% Evaluación Formativa')),
                ('porcentaje_sumativo', models.IntegerField(default=30, verbose_name='% Evaluación Sumativa')),
                ('nota_minima', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('nota_maxima', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=4)),
                ('nota_aprobacion', models.DecimalField(decimal_places=2, default=Decimal('7.00'), max_digits=4)),
                ('nota_supletorio', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=4)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
            },
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaturas', to='calificaciones.docente', verbose_name='Docente'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='calificaciones.asignatura', verbose_name='Asignatura'),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['estudiante', 'asignatura', 'trimestre'], name='calificacio_estudia_3c25d3_idx'),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['trimestre'], name='calificacio_trimest_e08959_idx'),
        ),
        migrations.AddField(
            model_name='auditoriacalificaciones',
            name='calificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calificaciones.calificacion'),
        ),
        migrations.AddField(
            model_name='auditoriacalificaciones',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
